apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app.kubernetes.io/name: calico-kube-controllers
    k8s-app: calico-kube-controllers
  name: calico-kube-controllers
  namespace: calico-system
  ownerReferences:
  - apiVersion: operator.tigera.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Installation
    name: default
    uid: "<UID>"
  resourceVersion: "835"
  uid: "<UID>"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: calico-kube-controllers
        k8s-app: calico-kube-controllers
      name: calico-kube-controllers
      namespace: calico-system
    spec:
      containers:
      - env:
        - name: KUBE_CONTROLLERS_CONFIG_NAME
          value: default
        - name: DATASTORE_TYPE
          value: kubernetes
        - name: ENABLED_CONTROLLERS
          value: node
        - name: FIPS_MODE_ENABLED
          value: "false"
        - name: KUBERNETES_SERVICE_HOST
          value: "<API server host>"
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
        image: docker.io/calico/kube-controllers:v3.24.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /usr/bin/check-status
            - -l
          failureThreshold: 6
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: calico-kube-controllers
        readinessProbe:
          exec:
            command:
            - /usr/bin/check-status
            - -r
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: calico-kube-controllers
      serviceAccountName: calico-kube-controllers
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      - key: CriticalAddonsOnly
        operator: Exists
