apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-10-26T19:59:53Z"
  generation: 1
  labels:
    app.kubernetes.io/name: calico-typha
    k8s-app: calico-typha
  name: calico-typha
  namespace: calico-system
  ownerReferences:
  - apiVersion: operator.tigera.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Installation
    name: default
    uid: "<UID>"
  resourceVersion: "766"
  uid: "<UID>"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      k8s-app: calico-typha
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        hash.operator.tigera.io/tigera-ca-private: "<hash>"
        hash.operator.tigera.io/typha-certs: "<hash>"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: calico-typha
        k8s-app: calico-typha
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - calico-typha
              topologyKey: topology.kubernetes.io/zone
            weight: 1
      containers:
      - env:
        - name: TYPHA_LOGSEVERITYSCREEN
          value: info
        - name: TYPHA_LOGFILEPATH
          value: none
        - name: TYPHA_LOGSEVERITYSYS
          value: none
        - name: TYPHA_CONNECTIONREBALANCINGMODE
          value: kubernetes
        - name: TYPHA_DATASTORETYPE
          value: kubernetes
        - name: TYPHA_HEALTHENABLED
          value: "true"
        - name: TYPHA_HEALTHPORT
          value: "9098"
        - name: TYPHA_K8SNAMESPACE
          value: calico-system
        - name: TYPHA_CAFILE
          value: /etc/pki/tls/certs/tigera-ca-bundle.crt
        - name: TYPHA_SERVERCERTFILE
          value: /typha-certs/tls.crt
        - name: TYPHA_SERVERKEYFILE
          value: /typha-certs/tls.key
        - name: TYPHA_FIPSMODEENABLED
          value: "false"
        - name: TYPHA_CLIENTCN
          value: typha-client
        - name: KUBERNETES_SERVICE_HOST
          value: "<API server host>"
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
        image: docker.io/calico/typha:v3.24.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            host: localhost
            path: /liveness
            port: 9098
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: calico-typha
        ports:
        - containerPort: 5473
          hostPort: 5473
          name: calico-typha
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            host: localhost
            path: /readiness
            port: 9098
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/pki/tls/certs/
          name: tigera-ca-bundle
          readOnly: true
        - mountPath: /typha-certs
          name: typha-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: calico-typha
      serviceAccountName: calico-typha
      terminationGracePeriodSeconds: 0
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: tigera-ca-bundle
        name: tigera-ca-bundle
      - name: typha-certs
        secret:
          defaultMode: 420
          secretName: typha-certs
